[project]
name = "mert"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "datasets>=2.19.1",
    "librosa>=0.11.0",
    "matplotlib>=3.10.8",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
    "torchvision>=0.20.1",
    "transformers==4.38.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"
